# Generated by Django 5.2.4 on 2025-07-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20250709_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bieth_date',
            new_name='birth_date',
        ),
    ]
